plugins { id 'com.android.application' }
android {
    namespace 'br.com.thigas.coder'
    compileSdk 35
    defaultConfig {
        applicationId 'br.com.thigas.coder'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
